#!/usr/bin/env python3
"""Generate the Unicode P* (Punctuation) range table used by
`is_unicode_punctuation` (regex `\\p{P}` classes) and, through
`is_hf_punctuation`, the Bert/Punctuation pre-tokenizer classifier.

The table is derived EMPIRICALLY from the parity target: Python
`tokenizers` 0.22.2's BertPreTokenizer isolation behavior (Rust
unicode-categories under the hood), sweeping planes 0-2. This keeps the
table exact w.r.t. the behavioral-comparison baseline regardless of the
local Python's unicodedata version.

ASCII symbols ($ + < = > ^ ` | ~) are excluded here on purpose so the
table matches regex `\\p{P}` semantics; `is_hf_punctuation` unions them
back via `is_ascii_punctuation`, mirroring HF's classifier.

Output: src/common/unicode_punct_data.mbt
"""
import os

from tokenizers import pre_tokenizers

OUT = os.path.join(
    os.path.dirname(__file__), "..", "src", "common", "unicode_punct_data.mbt"
)

bp = pre_tokenizers.BertPreTokenizer()

# is_ascii_punctuation minus these symbols == ASCII P* members.
ASCII_SYMBOLS = {0x24, 0x2B, 0x3C, 0x3D, 0x3E, 0x5E, 0x60, 0x7C, 0x7E}


def hf_is_punct(cp: int) -> bool:
    ch = chr(cp)
    if 0xD800 <= cp <= 0xDFFF:
        return False
    try:
        pieces = bp.pre_tokenize_str("a" + ch + "b")
    except Exception:  # noqa: BLE001
        return False
    # a | ch | b  <=> isolated as punctuation
    return len(pieces) == 3


def main() -> None:
    cps = [cp for cp in range(0x21, 0x30000) if hf_is_punct(cp) and cp not in ASCII_SYMBOLS]
    ranges = []
    for cp in cps:
        if ranges and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    lines = [
        "// GENERATED by scripts/gen_unicode_punct.py - Unicode P* ranges as",
        "// classified by Python `tokenizers` 0.22.2 (empirical sweep of the",
        "// BertPreTokenizer classifier, planes 0-2). Do not edit by hand;",
        "// regenerate with: python3 scripts/gen_unicode_punct.py",
        "// ASCII symbols are excluded for \\p{P} semantics; is_hf_punctuation",
        "// unions them back via is_ascii_punctuation.",
        "",
        "///|",
        "/// Inclusive [start, stop] codepoint ranges of Unicode P*",
        "/// (Punctuation) characters, sorted ascending.",
        "pub fn unicode_punct_ranges() -> Array[(Int, Int)] {",
        "  [",
    ]
    row = []
    for start, stop in ranges:
        row.append(f"({start}, {stop})")
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines += ["  ]", "}"]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(ranges)} ranges ({len(cps)} codepoints) -> {OUT}")


if __name__ == "__main__":
    main()
