#!/usr/bin/env python3
"""Generate the minimal accent-stripping table used by StripAccents /
BertNormalizer.

HuggingFace's strip_accents == NFD then drop all Mn (Nonspacing_Mark) chars.
We precompute, for every character whose NFD contains an Mn, the result of
that operation. This is a small table (~1000 entries).

Output: src/normalizer/accents_data.mbt  (a function returning the entries)
"""
import os
import unicodedata as ud

OUT = os.path.join(
    os.path.dirname(__file__), "..", "src", "normalizer", "accents_data.mbt"
)


def strip_accents(c: str) -> str:
    nfd = ud.normalize("NFD", c)
    return "".join(ch for ch in nfd if ud.category(ch) != "Mn")


def main() -> None:
    entries = []
    for cp in range(0x20000):
        c = chr(cp)
        nfd = ud.normalize("NFD", c)
        if nfd != c and any(ud.category(x) == "Mn" for x in nfd):
            stripped = strip_accents(c)
            if stripped != c:
                entries.append((cp, stripped))

    out = [
        "// AUTO-GENERATED by scripts/gen_accents.py — do not edit.",
        "// code point -> accent-stripped form (Unicode NFD minus Mn marks).",
        "",
        "///|",
        "pub fn accent_entries() -> Array[(Int, String)] {",
        "  [",
    ]
    for cp, stripped in entries:
        esc = stripped.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'    ({cp}, "{esc}"),')
    out.append("  ]")
    out.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {len(entries)} accent entries to {OUT}")


if __name__ == "__main__":
    main()
