#!/usr/bin/env python3
"""Generate Unicode normalization tables (NFC/NFD/NFKC/NFKD) into a .mbt file.

We export three tables, packed as newline-separated "hex:..." text constants
(parsed lazily at first use):

  - canonical decomposition:  cp -> sequence of cps (recursively fully decomposed)
  - compatibility decomposition: cp -> sequence of cps (full, used by NFKC/NFKD)
  - combining class (CCC):     cp -> ccc  (only nonzero)
  - canonical composition:     (cp_a, cp_b) -> cp  (primary composites only,
                               excluding composition-exclusions / non-starters)

Output: src/normalizer/unicode_norm_data.mbt
"""
import os
import sys
import unicodedata as ud

OUT = os.path.join(
    os.path.dirname(__file__), "..", "src", "normalizer", "unicode_norm_data.mbt"
)

MAXCP = 0x110000


def full_decomp(cp: int, compat: bool) -> list[int]:
    """Recursively fully decompose a code point (canonical or compatibility)."""
    c = chr(cp)
    form = "NFKD" if compat else "NFD"
    s = ud.normalize(form, c)
    if s == c:
        return [cp]
    return [ord(x) for x in s]


def main() -> None:
    canon = []   # (cp, [cps])
    compat = []  # (cp, [cps])  only where it differs from canonical
    ccc = []     # (cp, ccc)
    for cp in range(MAXCP):
        c = chr(cp)
        ccv = ud.combining(c)
        if ccv != 0:
            ccc.append((cp, ccv))
        d_canon = full_decomp(cp, compat=False)
        if d_canon != [cp]:
            canon.append((cp, d_canon))
        d_compat = full_decomp(cp, compat=True)
        if d_compat != [cp] and d_compat != d_canon:
            compat.append((cp, d_compat))

    # Canonical composition pairs: for each canonical (non-compat) decomposition
    # of exactly two code points whose result is not a composition exclusion and
    # whose first char is a starter, (a,b) -> cp is composable.
    comp = []  # (a, b, cp)
    for cp in range(MAXCP):
        # Only use the *direct* canonical decomposition (not recursive) here.
        dec = ud.decomposition(chr(cp))
        if not dec or dec.startswith("<"):
            continue  # no decomp or compatibility decomp
        parts = dec.split()
        if len(parts) != 2:
            continue
        a, b = int(parts[0], 16), int(parts[1], 16)
        # Exclude if the composite round-trips wrong under NFC (handles
        # composition exclusions and non-starter decompositions).
        if ud.normalize("NFC", chr(a) + chr(b)) != chr(cp):
            continue
        comp.append((a, b, cp))

    def emit_seq(pairs):
        # "hexcp:hex hex hex"
        return "\n".join(
            f"{cp:x}:" + " ".join(f"{x:x}" for x in seq) for cp, seq in pairs
        )

    lines = [
        "// AUTO-GENERATED by scripts/gen_unicode_norm.py — do not edit.",
        "// Unicode normalization tables (NFC/NFD/NFKC/NFKD).",
        "",
        "///|",
        f'pub fn canonical_decomp_raw() -> String {{\n  {raw(emit_seq(canon))}\n}}',
        "",
        "///|",
        f'pub fn compat_decomp_raw() -> String {{\n  {raw(emit_seq(compat))}\n}}',
        "",
        "///|",
        f'pub fn ccc_raw() -> String {{\n  {raw(chr(10).join(f"{cp:x}:{v}" for cp,v in ccc))}\n}}',
        "",
        "///|",
        f'pub fn composition_raw() -> String {{\n  {raw(chr(10).join(f"{a:x} {b:x} {cp:x}" for a,b,cp in comp))}\n}}',
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(
        f"canon={len(canon)} compat={len(compat)} ccc={len(ccc)} comp={len(comp)}"
    )


def raw(s: str) -> str:
    """Emit a MoonBit double-quoted string literal with \\n escapes."""
    esc = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return '"' + esc + '"'


if __name__ == "__main__":
    main()
