#!/usr/bin/env python3
"""Generate the Unicode `\\w` word-character range table used by
`is_word_char` (regex `\\w`/`\\W`, `[\\w]`-bracket spellings, and every
kind-4/13 family built on them).

The table is derived EMPIRICALLY from the parity target: Python
`tokenizers` 0.22.2's onig `\\w`, probed over planes 0-2 codepoint by
codepoint (a local unicodedata category filter proved unreliable — the
host Python carries Unicode 13.0 while onig tracks a newer Unicode, so
codepoints like U+2C2F/U+9FFD that became letters in Unicode 14+ were
missed). Probing uses a content-swap pair ('#'/'@') so a `#` input
character cannot masquerade as a match.

Output: src/common/unicode_word_data.mbt
"""
import json
import os

from tokenizers import Tokenizer

OUT = os.path.join(
    os.path.dirname(__file__), "..", "src", "common", "unicode_word_data.mbt"
)


def build(content):
    return Tokenizer.from_str(json.dumps({
        "version": "1.0",
        "normalizer": {
            "type": "Replace",
            "pattern": {"Regex": "\\w"},
            "content": content,
        },
        "model": {"type": "WordLevel", "vocab": {"x": 0}, "unk_token": "x"},
    }))


def main() -> None:
    hash_tok = build("#")
    at_tok = build("@")
    matched = []
    for cp in range(0, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        if hash_tok.normalizer.normalize_str(ch) == "#" and \
                at_tok.normalizer.normalize_str(ch) == "@":
            matched.append(cp)
    ranges = []
    for cp in matched:
        if ranges and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    lines = [
        "// GENERATED by scripts/gen_unicode_word.py — Unicode \\w ranges as",
        "// matched by Python `tokenizers` 0.22.2's onig \\w (empirical sweep",
        "// over the full Unicode range with a content-swap probe; supersedes a category-",
        "// based derivation that missed Unicode-14+ additions). Do not edit",
        "// by hand; regenerate with: python3 scripts/gen_unicode_word.py",
        "",
        "///|",
        "/// Inclusive [start, stop] codepoint ranges of Unicode \\w word",
        "/// characters, sorted ascending.",
        "pub fn unicode_word_ranges() -> Array[(Int, Int)] {",
        "  [",
    ]
    row = []
    for start, stop in ranges:
        row.append(f"({start}, {stop})")
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines += ["  ]", "}"]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(ranges)} empirical ranges ({len(matched)} codepoints) -> {OUT}")


if __name__ == "__main__":
    main()
