#!/usr/bin/env python3
"""Generate the Python `re` \\w word-character range table used by
`is_python_word_char` (Hub repo-id validation shape checks).

The table is derived EMPIRICALLY from the parity target: the installed
Python pair's `re.match(r'\\w', ch)` (equivalently `ch.isalnum() or
ch == '_'`), probed over the full codepoint range 0..0x10FFFF. This is
deliberately NOT the onig \\w table (unicode_word_data.mbt) nor the
\\p{L} approximation in is_unicode_letter: Python's \\w is General
Category L ∪ N plus '_' — it rejects the combining marks, connector
punctuation, and symbols onig accepts, and accepts all letters and
numbers including No numerals.

Output: src/common/python_word_data.mbt
"""
import os
import re

OUT = os.path.join(
    os.path.dirname(__file__), "..", "src", "common", "python_word_data.mbt"
)


def main() -> None:
    w = re.compile(r"\w")
    ranges = []
    start = None
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            is_word = False  # surrogates are not matchable characters
        else:
            is_word = bool(w.match(chr(cp)))
        if is_word and start is None:
            start = cp
        elif not is_word and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))

    total = sum(b - a + 1 for a, b in ranges)
    lines = []
    lines.append(
        "// GENERATED by scripts/gen_python_word.py — Python re \\w ranges"
    )
    lines.append(
        "// (empirical sweep of the installed Python's re.match(r'\\w', ch)"
    )
    lines.append(
        "// over the full codepoint range; General Category L ∪ N plus '_')."
    )
    lines.append(
        "// Do not edit by hand; regenerate with: python3 scripts/gen_python_word.py"
    )
    lines.append("")
    lines.append("///|")
    lines.append(
        "/// Inclusive [start, stop] codepoint ranges of Python re \\w word"
    )
    lines.append("/// characters, sorted ascending.")
    lines.append("let python_word_ranges : Array[(Int, Int)] = [")
    for a, b in ranges:
        lines.append(f"  ({a}, {b}),")
    lines.append("]")
    body = "\n".join(lines) + "\n"

    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {len(ranges)} ranges ({total} codepoints) to {OUT}")


if __name__ == "__main__":
    main()
