#!/usr/bin/env python3
"""Generate the Unicode `\\p{N}` number-character range table used by
`is_unicode_number` (regex `\\p{N}`/`\\p{Number}` spellings and every
kind-28/29 family built on them; General Category N = Nd + Nl + No).

Derived EMPIRICALLY from the parity target: Python `tokenizers` 0.22.2's
onig `\\p{N}`, probed over the full Unicode range codepoint by codepoint
(a local unicodedata category filter proved unreliable for \\w — the host
Python carries an older Unicode than onig — so the same empirical method
is used here). Probing uses a content-swap pair ('#'/'@') so a '#'
input character cannot masquerade as a match.

Output: src/common/unicode_number_data.mbt
"""
import json
import os

from tokenizers import Tokenizer

OUT = os.path.join(
    os.path.dirname(__file__), "..", "src", "common", "unicode_number_data.mbt"
)


def build(pattern, content):
    return Tokenizer.from_str(json.dumps({
        "version": "1.0",
        "normalizer": {
            "type": "Replace",
            "pattern": {"Regex": pattern},
            "content": content,
        },
        "model": {"type": "WordLevel", "vocab": {"x": 0}, "unk_token": "x"},
    }))


def sweep(pattern):
    hash_tok = build(pattern, "#")
    at_tok = build(pattern, "@")
    matched = []
    for cp in range(0, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        if hash_tok.normalizer.normalize_str(ch) == "#" and \
                at_tok.normalizer.normalize_str(ch) == "@":
            matched.append(cp)
    return matched


def to_ranges(matched):
    ranges = []
    for cp in matched:
        if ranges and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


def emit(name, doc, ranges):
    lines = [
        "///|",
        f"/// {doc} — module-level so hot paths pay no",
        "/// per-call allocation; consumers binary-search over it.",
        f"let {name} : Array[(Int, Int)] = [",
    ]
    for lo, hi in ranges:
        lines.append(f"  ({hex(lo)}, {hex(hi)}),")
    lines.append("]")
    lines.append("")
    return lines


def main() -> None:
    header = [
        "// GENERATED by scripts/gen_unicode_number.py — Unicode number",
        "// ranges as matched by Python `tokenizers` 0.22.2's onig",
        "// (empirical full-range sweep with a content-swap probe):",
        "// - number_ranges: \\p{N} (General Category N = Nd + Nl + No;",
        "//   supersedes the Nd-only mapping these spellings previously",
        "//   shared with \\d — probed: ² (No) matches \\p{N} not \\d)",
        "// - decimal_ranges: \\d (Nd; supersedes a hard-coded interval",
        "//   list that missed Unicode-14+ additions — probed: U+1FBF0",
        "//   MATHEMATICAL SANS-SERIF DIGIT ZERO matches HF \\d).",
        "// Do not edit by hand; regenerate with:",
        "// python3 scripts/gen_unicode_number.py",
        "",
    ]
    number = sweep("\\p{N}")
    decimal = sweep("\\d")
    body = emit(
        "number_ranges",
        "Unicode `\\p{N}` / `\\p{Number}` ranges (Nd + Nl + No) as probed"
        " from the parity target 0.22.2",
        to_ranges(number),
    ) + emit(
        "decimal_ranges",
        "Unicode `\\d` ranges (Nd) as probed from the parity target 0.22.2",
        to_ranges(decimal),
    )
    with open(OUT, "w") as f:
        f.write("\n".join(header + body))
    print(f"pN: {len(number)} codepoints in {len(to_ranges(number))} ranges")
    print(f"\\d:    {len(decimal)} codepoints in {len(to_ranges(decimal))} ranges -> {OUT}")
    import unicodedata
    drift = [cp for cp in number
             if unicodedata.category(chr(cp)) not in ("Nd", "Nl", "No")]
    print(f"{len(drift)} pN matches drift from host-unicodedata N "
          f"(onig tracks a newer Unicode); first few:")
    for cp in drift[:8]:
        print(f"  U+{cp:04X} host={unicodedata.category(chr(cp))}")


if __name__ == "__main__":
    main()
